name       : surfn-icon-theme
version    : 20.12.7
release    : 4
source     :
    - https://github.com/erikdubois/Surfn/archive/20.12-7.tar.gz : c943df79b84dd75218536a8c594713eec6bbde83dede115b97d7c6d337027cc4
    - https://github.com/erikdubois/Surfn/archive/9.7.1.tar.gz : 87816fbee125ac3ce93739128bc52adf99c8d81846222259733e7093d79db2a9
license    : CC-BY-NC-SA-4.0
component  :
    - desktop.theme
    - ^surfn-icon-theme : desktop.theme
    - ^surfn-arc-icon-theme : desktop.theme
    - ^surfn-arch-blue-icon-theme : desktop.theme
    - ^surfn-arched-icon-theme : desktop.theme
    - ^surfn-breeze-arc-icon-theme : desktop.theme
    - ^surfn-breeze-dark-icon-theme : desktop.theme
    - ^surfn-evopop-icon-theme : desktop.theme
    - ^surfn-luv-red-icon-theme : desktop.theme
    - ^surfn-luv-icon-theme : desktop.theme
    - ^surfn-majestic-icon-theme : desktop.theme
    - ^surfn-mint-x-grey-icon-theme : desktop.theme
    - ^surfn-numix-misty-icon-theme : desktop.theme
    - ^surfn-numix-polo-icon-theme : desktop.theme
    - ^surfn-numix-icon-theme : desktop.theme
    - ^surfn-orange-icon-theme : desktop.theme
    - ^surfn-papirus-blue-icon-theme : desktop.theme
    - ^surfn-papirus-grey-icon-theme : desktop.theme
    - ^surfn-vertexed-icon-theme : desktop.theme
summary    :
    - Surfn icon theme
    - ^surfn-icon-theme : Surfn icon theme
    - ^surfn-arc-icon-theme : Surfn Arc icon theme
    - ^surfn-arch-blue-icon-theme : Surfn Arch Blue icon theme
    - ^surfn-arched-icon-theme : Surfn Arched icon theme
    - ^surfn-breeze-arc-icon-theme : Surfn Breeze Arc icon theme
    - ^surfn-breeze-dark-icon-theme : Surfn Breeze Dark icon theme
    - ^surfn-evopop-icon-theme : Surfn Evopop icon theme
    - ^surfn-luv-red-icon-theme : Surfn Luv Red icon theme
    - ^surfn-luv-icon-theme : Surfn Luv icon theme
    - ^surfn-majestic-icon-theme : Surfn Majestic icon theme
    - ^surfn-mint-x-grey-icon-theme : Surfn Mint X Grey icon theme
    - ^surfn-numix-misty-icon-theme : Surfn Numix Misty icon theme
    - ^surfn-numix-polo-icon-theme : Surfn Numix Polo icon theme
    - ^surfn-numix-icon-theme : Surfn Numix icon theme
    - ^surfn-orange-icon-theme : Surfn Orange icon theme
    - ^surfn-papirus-blue-icon-theme : Surfn Papirus Blue icon theme
    - ^surfn-papirus-grey-icon-theme : Surfn Papirus Greyicon theme
    - ^surfn-vertexed-icon-theme : Surfn Vertexed icon theme
description:
    - Surfn icon theme
    - ^surfn-icon-theme : Surfn icon theme
    - ^surfn-arc-icon-theme : Surfn Arc icon theme
    - ^surfn-arch-blue-icon-theme : Surfn Arch Blue icon theme
    - ^surfn-arched-icon-theme : Surfn Arched icon theme
    - ^surfn-breeze-arc-icon-theme : Surfn Breeze Arc icon theme
    - ^surfn-breeze-dark-icon-theme : Surfn Breeze Dark icon theme
    - ^surfn-evopop-icon-theme : Surfn Evopop icon theme
    - ^surfn-luv-red-icon-theme : Surfn Luv Red icon theme
    - ^surfn-luv-icon-theme : Surfn Luv icon theme
    - ^surfn-majestic-icon-theme : Surfn Majestic icon theme
    - ^surfn-mint-x-grey-icon-theme : Surfn Mint X Grey icon theme
    - ^surfn-numix-misty-icon-theme : Surfn Numix Misty icon theme
    - ^surfn-numix-polo-icon-theme : Surfn Numix Polo icon theme
    - ^surfn-numix-icon-theme : Surfn Numix icon theme
    - ^surfn-orange-icon-theme : Surfn Orange icon theme
    - ^surfn-papirus-blue-icon-theme : Surfn Papirus Blue icon theme
    - ^surfn-papirus-grey-icon-theme : Surfn Papirus Greyicon theme
    - ^surfn-vertexed-icon-theme : Surfn Vertexed icon theme
patterns   :
    - ^surfn-icon-theme : /usr/share/icons/*
    - ^surfn-arc-icon-theme : /usr/share/icons/*-Arc
    - ^surfn-arch-blue-icon-theme : /usr/share/icons/*-Arch-Blue
    - ^surfn-arched-icon-theme : /usr/share/icons/*-Arched
    - ^surfn-breeze-arc-icon-theme : /usr/share/icons/*-Breeze-Arc
    - ^surfn-breeze-dark-icon-theme : /usr/share/icons/*-Breeze-Dark
    - ^surfn-evopop-icon-theme : /usr/share/icons/*-Evopop
    - ^surfn-luv-red-icon-theme : /usr/share/icons/*-Luv-Red
    - ^surfn-luv-icon-theme : /usr/share/icons/*-Luv
    - ^surfn-majestic-icon-theme : /usr/share/icons/*-Majestic
    - ^surfn-mint-x-grey-icon-theme : /usr/share/icons/*-Mint-X-Grey
    - ^surfn-numix-misty-icon-theme : /usr/share/icons/*-Numix-Misty
    - ^surfn-numix-polo-icon-theme : /usr/share/icons/*-Numix-Polo
    - ^surfn-numix-icon-theme : /usr/share/icons/*-Numix
    - ^surfn-orange-icon-theme : /usr/share/icons/*-Orange
    - ^surfn-papirus-blue-icon-theme : /usr/share/icons/*-Papirus-Blue
    - ^surfn-papirus-grey-icon-theme : /usr/share/icons/*-Papirus-Grey
    - ^surfn-vertexed-icon-theme : /usr/share/icons/*-Vertexed
rundeps    :
    - ^surfn-arc-icon-theme : surfn-icon-theme
    - ^surfn-arch-blue-icon-theme : surfn-icon-theme
    - ^surfn-arched-icon-theme : surfn-icon-theme
    - ^surfn-breeze-arc-icon-theme : surfn-icon-theme
    - ^surfn-breeze-dark-icon-theme : surfn-icon-theme
    - ^surfn-evopop-icon-theme : surfn-icon-theme
    - ^surfn-luv-red-icon-theme : surfn-icon-theme
    - ^surfn-luv-icon-theme : surfn-icon-theme
    - ^surfn-majestic-icon-theme : surfn-icon-theme
    - ^surfn-mint-x-grey-icon-theme : surfn-icon-theme
    - ^surfn-numix-misty-icon-theme : surfn-icon-theme
    - ^surfn-numix-polo-icon-theme : surfn-icon-theme
    - ^surfn-numix-icon-theme : surfn-icon-theme
    - ^surfn-orange-icon-theme : surfn-icon-theme
    - ^surfn-papirus-blue-icon-theme : surfn-icon-theme
    - ^surfn-papirus-grey-icon-theme : surfn-icon-theme
    - ^surfn-vertexed-icon-theme : surfn-icon-theme
install    : |
    install -dm00644 $installdir/usr/share/icons/
    cp -r ./surfn-icons/Surfn* $installdir/usr/share/icons/
    # extract Evopop theme from previous version (removed in current version)
    tar xf $sources/9.7.1.tar.gz -C $workdir
    cp -r $workdir/Surfn-9.7.1/surfn-icons/Surfn-Evopop $installdir/usr/share/icons/
    chmod -R 00644 $installdir/usr/share/icons/*

    # remove cache
    rm -rf $installdir/usr/share/icons/Surfn*/icon-theme.cache
    rm -rf $installdir/usr/share/icons/Surfn*/create-new-icon-theme.cache.sh
